// Every Fabric tenant setting this tenant exposes (169 at time of capture), generated by
// scripts/get-tenant-settings.ps1 -AsBicepParam -Sanitise.
//
// This is a reference template, not a deployable param file as-is:
//   - Security group object IDs and names are placeholders. Fill in the four service-principal
//     settings that need them, or drop enabledSecurityGroups to leave a setting unscoped.
//   - enabled values are a snapshot of one tenant's posture. Review before applying - deploying
//     this wholesale asserts all 169 settings, including disabling anything currently off.
//
// The intended workflow is to copy the entries you actually want to manage into main.bicepparam
// rather than deploying this file directly. Regenerate without -Sanitise for a local working copy
// with real group IDs (main.local.bicepparam is gitignored for exactly that).
using 'main.bicep'
param tenantSettings = [
  // Microsoft Entra single sign-on for data gateway
  {
    name: 'AADSSOForGateway'
    enabled: true
  }
  // Microsoft Entra single sign-on for virtual network (VNet) data gateway
  {
    name: 'AADSSOForVnetGateway'
    enabled: false
  }
  // Enhance admin APIs responses with detailed metadata
  {
    name: 'AdminApisIncludeDetailedMetadata'
    enabled: false
  }
  // Enhance admin APIs responses with DAX and mashup expressions
  {
    name: 'AdminApisIncludeExpressions'
    enabled: false
  }
  // Show a custom message before publishing reports
  {
    name: 'AdminCustomDisclaimer'
    enabled: false
    properties: [
      {
        name: 'AdminCustomDisclaimer'
        value: ''
        type: 'Freetext'
      }
    ]
  }
  // Users with view permission can launch Explore
  {
    name: 'AdminDataExploreViewPermission'
    enabled: true
  }
  // Enable sending Operations Agents observability data to Agent 365 (preview)
  {
    name: 'AllowA365Observability'
    enabled: false
    delegateToCapacity: true
  }
  // Tenant-level Private Link
  {
    name: 'AllowAccessOverPrivateLinks'
    enabled: false
  }
  // Show user data in the Fabric Capacity Metrics app and reports
  {
    name: 'AllowCapacityMetricsReportUserMask'
    enabled: true
  }
  // AppSource Custom Visuals SSO
  {
    name: 'AllowCVAuthenticationTenant'
    enabled: false
  }
  // Allow access to the browser's local storage
  {
    name: 'AllowCVLocalStorageV2Tenant'
    enabled: true
  }
  // Allow downloads from custom visuals
  {
    name: 'AllowCVToExportDataToFileTenant'
    enabled: false
  }
  // Endorse master data
  {
    name: 'AllowEndorsementMasterDataSwitch'
    enabled: false
  }
  // Users can accept external data shares
  {
    name: 'AllowExternalDataSharingReceiverSwitch'
    enabled: false
  }
  // External data sharing
  {
    name: 'AllowExternalDataSharingSwitch'
    enabled: false
  }
  // Users can try Microsoft Fabric paid features
  {
    name: 'AllowFreeTrial'
    enabled: true
  }
  // Use short-lived user-delegated SAS tokens
  {
    name: 'AllowGetOneLakeUDK'
    enabled: true
  }
  // Users can see guest users in lists of suggested people
  {
    name: 'AllowGuestLookup'
    enabled: false
  }
  // Guest users can access Microsoft Fabric
  {
    name: 'AllowGuestUserToAccessSharedContent'
    enabled: false
  }
  // Allow non-Entra ID auth in Eventstream
  {
    name: 'AllowNonEntraADAuthInEventStream'
    enabled: true
  }
  // Users with read or write permission can download data from notebooks
  {
    name: 'AllowNotebookDataExport'
    enabled: true
  }
  // Authenticate with OneLake user-delegated SAS tokens
  {
    name: 'AllowOneLakeUDK'
    enabled: false
    delegateToWorkspace: true
  }
  // Insights for operations agents (preview)
  {
    name: 'AllowOperatorInsightsTenantSwitch'
    enabled: true
    delegateToCapacity: true
  }
  // Allow DirectQuery connections to Power BI semantic models
  {
    name: 'AllowPowerBIASDQOnTenant'
    enabled: false
  }
  // Data sent to Azure OpenAI can be processed outside your capacity's geographic region, compliance boundary, or national cloud instance
  {
    name: 'AllowSendAOAIDataToOtherRegions'
    enabled: false
    delegateToCapacity: false
  }
  // Allow service principals to create and use profiles
  {
    name: 'AllowServicePrincipalsCreateAndUseProfiles'
    enabled: true
  }
  // Service principals can access read-only admin APIs
  {
    name: 'AllowServicePrincipalsUseReadAdminAPIs'
    enabled: true
    enabledSecurityGroups: [
      {
        graphId: '<security-group-object-id>'
        name: '<security-group-name>'
      }
    ]
  }
  // Service principals can access admin APIs used for updates
  {
    name: 'AllowServicePrincipalsUseWriteAdminAPIs'
    enabled: true
    enabledSecurityGroups: [
      {
        graphId: '<security-group-object-id>'
        name: '<security-group-name>'
      }
    ]
  }
  // Data sent to Azure OpenAI can be stored outside your capacity's geographic region, compliance boundary, or national cloud instance
  {
    name: 'AllowStoreAOAIDataInOtherRegions'
    enabled: false
  }
  // Allow data processing outside geographic region for Azure AI services
  {
    name: 'AllowUserDataProcessedByAiServicesOutOfGeo'
    enabled: false
    delegateToCapacity: false
  }
  // Enable Fabric App Items (preview)
  {
    name: 'AppBackendTenant'
    enabled: false
    delegateToCapacity: true
  }
  // Push apps to end users
  {
    name: 'AppPush'
    enabled: true
  }
  // Users can create Azure Databricks Storage items (preview)
  {
    name: 'ArtifactDatabricksStoragePreview'
    enabled: false
    delegateToCapacity: true
  }
  // Users can create dbt job items (preview)
  {
    name: 'ArtifactDBTItemTenantSwitch'
    enabled: false
    delegateToCapacity: false
  }
  // Enable new mirrored catalog items (preview)
  {
    name: 'ArtifactMirroredCatalogPreview'
    enabled: false
    delegateToCapacity: true
  }
  // Use global search for Power BI
  {
    name: 'ArtifactSearchTenant'
    enabled: false
  }
  // Microsoft can store query text to aid in support investigations
  {
    name: 'ASCollectQueryTextTelemetryTenantSwitch'
    enabled: false
  }
  // Enable granular access control for all data connections
  {
    name: 'ASShareableCloudConnectionBindingSecurityModeTenant'
    enabled: true
  }
  // Semantic models can export data to OneLake
  {
    name: 'ASWritethruContinuousExportTenantSwitch'
    enabled: true
  }
  // Install Power BI app for Microsoft Teams automatically
  {
    name: 'AutoInstallPowerBIAppInTeamsTenant'
    enabled: true
  }
  // Show entry points for insights (preview)
  {
    name: 'AutomatedInsightsEntryPoints'
    enabled: false
  }
  // Receive notifications for top insights (preview)
  {
    name: 'AutomatedInsightsTenant'
    enabled: false
  }
  // Automatically convert and store reports using Power BI enhanced metadata format (PBIR) (preview)
  {
    name: 'AutomaticallyUsePBIR'
    enabled: false
  }
  // Users can use the Azure Maps visual
  {
    name: 'AzureMaps'
    enabled: true
  }
  // Data sent to Azure Maps can be processed outside your tenant's geographic region, compliance boundary, or national cloud instance
  {
    name: 'AzureMapsCrossRegionDataProcessing'
    enabled: true
  }
  // Users can use Azure Maps services
  {
    name: 'AzureMapsInFabric'
    enabled: true
  }
  // Data sent to Azure Maps can be processed outside your capacity's geographic region, compliance boundary or national cloud instance
  {
    name: 'AzureMapsInFabricCrossRegionDataProcessing'
    enabled: false
  }
  // Data sent to Azure Maps can be processed by Microsoft Online Services Subprocessors 
  {
    name: 'AzureMapsThirdPartyDataProcessing'
    enabled: false
  }
  // Users can use Azure Maps Weather Services (Preview)
  {
    name: 'AzureMapsWeatherServices'
    enabled: true
  }
  // Map and filled map visuals
  {
    name: 'BingMap'
    enabled: false
  }
  // Block Public Internet Access
  {
    name: 'BlockAccessFromPublicNetworks'
    enabled: false
  }
  // Block republish and disable package refresh
  {
    name: 'BlockAutoDiscoverAndPackageRefresh'
    enabled: false
  }
  // Restrict content with protected labels from being shared via link with everyone in your organization
  {
    name: 'BlockProtectedLabelSharingToEntireOrg'
    enabled: false
  }
  // Block ResourceKey Authentication
  {
    name: 'BlockResourceKeyAuthentication'
    enabled: true
  }
  // Create and use Gen1 dataflows
  {
    name: 'CDSAManagement'
    enabled: true
  }
  // Add and use certified visuals only (block uncertified)
  {
    name: 'CertifiedCustomVisualsTenant'
    enabled: true
  }
  // Certification
  {
    name: 'CertifyDatasets'
    enabled: true
    delegateToDomain: false
    properties: [
      {
        name: 'CertificationDocumentationUrl'
        value: ''
        type: 'Url'
      }
    ]
  }
  // Fabric item recovery
  {
    name: 'ConfigureArtifactRetentionPeriod'
    enabled: false
    properties: [
      {
        name: 'ArtifactRetentionPeriod'
        value: ''
        type: 'Integer'
      }
    ]
  }
  // Define maximum number of Fabric identities in a tenant
  {
    name: 'ConfigureFabricIdentityTenantLimit'
    enabled: false
    properties: [
      {
        name: 'FabricIdentityTenantLimit'
        value: ''
        type: 'Integer'
      }
    ]
  }
  // Define workspace retention period
  {
    name: 'ConfigureFolderRetentionPeriod'
    enabled: true
    properties: [
      {
        name: 'FolderRetentionPeriod'
        value: '30'
        type: 'Integer'
      }
    ]
  }
  // Configure workspace-level IP firewall rules and trusted resource instances 
  {
    name: 'ConfigureWorkspaceLevelIPFirewallRules'
    enabled: true
  }
  // Capacities can be designated as Fabric Copilot capacities
  {
    name: 'CopilotCapacitySetupPermissionSwitch'
    enabled: true
  }
  // Create workspaces
  {
    name: 'CreateAppWorkspaces'
    enabled: true
  }
  // Allow visuals created using the Power BI SDK
  {
    name: 'CustomVisualsTenant'
    enabled: true
  }
  // Create Datamarts (preview)
  {
    name: 'DatamartTenant'
    enabled: false
  }
  // Allow Microsoft Purview to secure AI interactions
  {
    name: 'DataSecurityForAIInteractions'
    enabled: false
  }
  // Semantic Model Execute Queries REST API
  {
    name: 'DatasetExecuteQueries'
    enabled: false
  }
  // Enable Denodo SSO
  {
    name: 'DenodoForPowerBISSO'
    enabled: false
  }
  // Publish template apps
  {
    name: 'DevelopServiceApps'
    enabled: false
  }
  // Users can create Digital Twin Builder (preview) items
  {
    name: 'DigitalOperationsPreview'
    enabled: false
    delegateToCapacity: true
  }
  // Discover content
  {
    name: 'DiscoverDatasetsConsumption'
    enabled: true
  }
  // Make certified content discoverable 
  {
    name: 'DiscoverDatasetsSettingsCertified'
    enabled: true
  }
  // Make promoted content discoverable
  {
    name: 'DiscoverDatasetsSettingsPromoted'
    enabled: true
  }
  // Dremio SSO
  {
    name: 'DremioSSO'
    enabled: false
  }
  // Apply sensitivity labels from data sources to their data in Power BI
  {
    name: 'EimInformationProtectionDataSourceInheritanceSetting'
    enabled: false
  }
  // Domain admins can set default sensitivity labels for their domains (preview)
  {
    name: 'EimInformationProtectionDefaultLabelDomainSetting'
    enabled: false
  }
  // Automatically apply sensitivity labels to downstream content
  {
    name: 'EimInformationProtectionDownstreamInheritanceSetting'
    enabled: false
  }
  // Allow users to apply sensitivity labels for content
  {
    name: 'EimInformationProtectionEdit'
    enabled: false
  }
  // Allow workspace admins to override automatically applied sensitivity labels
  {
    name: 'EimInformationProtectionWorkspaceAdminsOverrideAutomaticLabelsSetting'
    enabled: false
  }
  // Guest users can browse and access Fabric content
  {
    name: 'ElevatedGuestsTenant'
    enabled: false
  }
  // Receive email and Teams notifications for service outages or incidents
  {
    name: 'EmailSecurityGroupsOnOutage'
    enabled: false
    properties: [
      {
        name: 'EmailList'
        value: ''
        type: 'MailEnabledSecurityGroup'
      }
    ]
  }
  // B2B guest users can set up and be subscribed to email subscriptions
  {
    name: 'EmailSubscriptionsToB2BUsers'
    enabled: false
  }
  // Users can send email subscriptions to external users
  {
    name: 'EmailSubscriptionsToExternalUsers'
    enabled: false
  }
  // Users can set up email subscriptions
  {
    name: 'EmailSubscriptionTenant'
    enabled: false
  }
  // Embed content in apps
  {
    name: 'Embedding'
    enabled: false
  }
  // Enable anonymous data access for Fabric Apps (Preview)
  {
    name: 'EnableAnonymousDataAccessForFabricApps'
    enabled: false
  }
  // Users can use Copilot and other features powered by Azure OpenAI
  {
    name: 'EnableAOAI'
    enabled: true
    delegateToCapacity: true
  }
  // Allow specific users to turn on external data sharing
  {
    name: 'EnableDatasetInPlaceSharing'
    enabled: false
  }
  // ArcGIS GeoAnalytics for Fabric Runtime
  {
    name: 'EnableEsriLibraries'
    enabled: true
    delegateToCapacity: true
  }
  // Allow tenant and domain admins to override workspace assignments (preview)
  {
    name: 'EnableReassignDataDomainSwitch'
    enabled: true
  }
  // Use ArcGIS Maps for Power BI
  {
    name: 'EsriVisual'
    enabled: true
  }
  // Enable Event Schema Sets in Real-Time Hub (preview)
  {
    name: 'EventDefinitionTenantSwitch'
    enabled: false
    delegateToCapacity: false
  }
  // Help Power BI optimize your experience
  {
    name: 'ExpFlightingTenant'
    enabled: false
  }
  // Download reports
  {
    name: 'ExportReport'
    enabled: true
  }
  // Export to .csv
  {
    name: 'ExportToCsv'
    enabled: false
  }
  // Export to Excel
  {
    name: 'ExportToExcelSetting'
    enabled: false
  }
  // Export reports as image files
  {
    name: 'ExportToImage'
    enabled: false
    delegateToWorkspace: false
    delegateToDomain: false
  }
  // Export reports as MHTML documents
  {
    name: 'ExportToMHTML'
    enabled: false
    delegateToWorkspace: false
    delegateToDomain: false
  }
  // Export reports as PowerPoint presentations or PDF documents
  {
    name: 'ExportToPowerPoint'
    enabled: false
    delegateToWorkspace: false
    delegateToDomain: false
  }
  // Export reports as Word documents
  {
    name: 'ExportToWord'
    enabled: false
    delegateToWorkspace: false
    delegateToDomain: false
  }
  // Export reports as XML documents
  {
    name: 'ExportToXML'
    enabled: false
    delegateToWorkspace: false
    delegateToDomain: false
  }
  // Copy and paste visuals
  {
    name: 'ExportVisualImageTenant'
    enabled: true
  }
  // Guest users can work with shared semantic models in their own tenants
  {
    name: 'ExternalDatasetSharingTenant'
    enabled: false
  }
  // Users can invite guest users to collaborate through item sharing and permissions
  {
    name: 'ExternalSharingV2'
    enabled: false
  }
  // Capacity admins and contributors can add and remove additional workloads
  {
    name: 'FabricAddPartnerWorkload'
    enabled: false
    properties: [
      {
        name: 'OnlyCapacityAdmins'
        value: 'false'
        type: 'Boolean'
      }
    ]
  }
  // Workspace admins can add and remove additional workloads (preview)
  {
    name: 'FabricAddWorkloadToWorkspace'
    enabled: true
  }
  // Product Feedback
  {
    name: 'FabricFeedbackTenantSwitch'
    enabled: true
  }
  // Users can create Fabric items
  {
    name: 'FabricGAWorkloads'
    enabled: true
    delegateToCapacity: true
  }
  // Users can be informed of upcoming conferences featuring Microsoft Fabric when they are logged in to Fabric
  {
    name: 'FabricPromotionTenantSwitch'
    enabled: true
  }
  // Workspace admins can develop partner workloads 
  {
    name: 'FabricThirdPartyWorkloads'
    enabled: false
  }
  // Users can sync workspace items with GitHub repositories 
  {
    name: 'GitHubTenantSettings'
    enabled: false
    delegateToWorkspace: false
    delegateToCapacity: false
  }
  // Users can export items to Git repositories in other geographical locations
  {
    name: 'GitIntegrationCrossGeoTenantSwitch'
    enabled: false
    delegateToWorkspace: false
    delegateToCapacity: false
  }
  // Users can export workspace items with applied sensitivity labels to Git repositories
  {
    name: 'GitIntegrationSensitivityLabelsTenantSwitch'
    enabled: false
    delegateToWorkspace: false
    delegateToCapacity: false
  }
  // Users can synchronize workspace items with their Git repositories
  {
    name: 'GitIntegrationTenantSwitch'
    enabled: false
    delegateToWorkspace: false
    delegateToCapacity: false
  }
  // Google BigQuery SSO
  {
    name: 'GoogleBigQuerySSO'
    enabled: false
  }
  // Users can access a standalone, cross-item Power BI Copilot experience (preview)
  {
    name: 'ImmersiveTenantAdminSwitch'
    enabled: false
  }
  // Receive In-product notifications for service outages or incidents
  {
    name: 'InProductOutageNotification'
    enabled: false
    delegateToWorkspace: false
    delegateToCapacity: false
  }
  // Install template apps not listed in AppSource
  {
    name: 'InstallNonvalidatedTemplateApps'
    enabled: false
  }
  // Install template apps
  {
    name: 'InstallServiceApps'
    enabled: true
  }
  // Users can work with semantic models in Excel using a live connection
  {
    name: 'LiveConnection'
    enabled: true
  }
  // Azure Log Analytics connections for workspace administrators
  {
    name: 'LogAnalyticsAttachForWorkspaceAdmins'
    enabled: false
  }
  // Share Fabric data with your Microsoft 365 services
  {
    name: 'M365DataSharing'
    enabled: false
    properties: [
      {
        name: 'M365DataSharingAcrossGeos'
        value: 'false'
        type: 'Boolean'
      }
    ]
  }
  // Fabric data agents can send operational metadata for observability in Microsoft Foundry
  {
    name: 'MicrosoftFoundryTelemetry'
    enabled: true
  }
  // ML models can serve real-time predictions from API endpoints (preview)
  {
    name: 'MLModelEndpointsTenantSwitch'
    enabled: false
  }
  // Semantic model owners can choose to automatically update semantic models from files imported from OneDrive or SharePoint
  {
    name: 'ODSPRefreshEnforcementTenantAllowAutomaticUpdate'
    enabled: false
  }
  // Users can share links to Power BI files stored in OneDrive and SharePoint through Power BI Desktop (preview)
  {
    name: 'OneDriveSharePointAllowSharingTenantSetting'
    enabled: true
  }
  // Users can view Power BI files saved in OneDrive and SharePoint (preview)
  {
    name: 'OneDriveSharePointViewerIntegrationTenantSettingV2'
    enabled: true
  }
  // Include end-user identifiers in OneLake diagnostic logs
  {
    name: 'OneLakeDiagnosticLogsEUII'
    enabled: true
  }
  // Users can sync data in OneLake with the OneLake File Explorer app
  {
    name: 'OneLakeFileExplorer'
    enabled: true
  }
  // Users can access data stored in OneLake with apps external to Fabric
  {
    name: 'OneLakeForThirdParty'
    enabled: false
  }
  // Allow XMLA endpoints and Analyze in Excel with on-premises semantic models
  {
    name: 'OnPremAnalyzeInExcel'
    enabled: false
  }
  // Users can create Ontology (preview) items
  {
    name: 'OntologyPreview'
    enabled: false
    delegateToCapacity: true
  }
  // Workspace admins can turn on monitoring for their workspaces (preview)
  {
    name: 'PlatformMonitoringTenantSetting'
    enabled: true
    delegateToCapacity: true
  }
  // Create and use Scorecards
  {
    name: 'PowerBIGoalsTenant'
    enabled: true
  }
  // Users can use the Power BI Model Context Protocol server endpoint (preview)
  {
    name: 'PowerBIMCP'
    enabled: false
  }
  // Only show approved items in the standalone Copilot in Power BI experience (preview)
  {
    name: 'PreppedForCopilotContentDiscovery'
    enabled: true
    delegateToWorkspace: true
    delegateToDomain: true
  }
  // Print dashboards and reports
  {
    name: 'Printing'
    enabled: false
  }
  // Featured content
  {
    name: 'PromoteContent'
    enabled: true
  }
  // Publish apps to the entire organization
  {
    name: 'PublishContentPack'
    enabled: true
  }
  // Publish to web
  {
    name: 'PublishToWeb'
    enabled: false
    properties: [
      {
        name: 'CreateP2w'
        value: 'false'
        type: 'Boolean'
      }
    ]
  }
  // Review questions
  {
    name: 'QnaFeedbackLoop'
    enabled: true
  }
  // Synonym sharing
  {
    name: 'QnaLsdlSharing'
    enabled: true
  }
  // Scale out queries for large semantic models
  {
    name: 'QueryScaleOutTenant'
    enabled: true
  }
  // Allow Real-Time Dashboards to include embedded app visuals
  {
    name: 'RealTimeDashboardEmbeddedApp'
    enabled: false
  }
  // Redshift SSO
  {
    name: 'RedshiftSSO'
    enabled: false
  }
  // Block users from reassigning personal workspaces (My Workspace)
  {
    name: 'RestrictMyFolderCapacity'
    enabled: false
  }
  // Interact with and share R and Python visuals
  {
    name: 'RScriptVisual'
    enabled: false
  }
  // Detect anomalies in Real-Time Intelligence (Preview)
  {
    name: 'RTHAnomalyDetectionTenantSwitch'
    enabled: false
    delegateToCapacity: false
  }
  // Service principals can create workspaces, connections, and deployment pipelines
  {
    name: 'ServicePrincipalAccessGlobalAPIs'
    enabled: true
    enabledSecurityGroups: [
      {
        graphId: '<security-group-object-id>'
        name: '<security-group-name>'
      }
    ]
  }
  // Service principals can call Fabric public APIs
  {
    name: 'ServicePrincipalAccessPermissionAPIs'
    enabled: true
    enabledSecurityGroups: [
      {
        graphId: '<security-group-object-id>'
        name: '<security-group-name>'
      }
    ]
  }
  // Allow shareable links to grant access to everyone in your organization
  {
    name: 'ShareLinkToEntireOrg'
    enabled: false
  }
  // Enable Microsoft Teams integration
  {
    name: 'ShareToTeamsTenant'
    enabled: true
  }
  // All Power BI users can see "Set alert" button to create Fabric Activator alerts
  {
    name: 'ShowActivatorEntryPointsTenantSwitch'
    enabled: false
  }
  // Snowflake SSO
  {
    name: 'SnowflakeSSO'
    enabled: false
  }
  // Enable Starburst SSO
  {
    name: 'StarburstAadSSO'
    enabled: false
  }
  // Enable Power BI add-in for PowerPoint
  {
    name: 'StorytellingTenant'
    enabled: true
  }
  // Create template organizational apps
  {
    name: 'TemplatePublish'
    enabled: false
  }
  // Publish "Get Help" information
  {
    name: 'TenantSettingPublishGetHelpInfo'
    enabled: false
    properties: [
      {
        name: 'TrainingDocumentation'
        value: ''
        type: 'Url'
      }
      {
        name: 'DiscussionForum'
        value: ''
        type: 'Url'
      }
      {
        name: 'LicensingRequests'
        value: ''
        type: 'Url'
      }
      {
        name: 'HelpDesk'
        value: ''
        type: 'Url'
      }
    ]
  }
  // Users can see and work with additional workloads not validated by Microsoft
  {
    name: 'ThirdPartyPrivateWorkloads'
    enabled: false
  }
  // Usage metrics for content creators
  {
    name: 'UsageMetrics'
    enabled: true
  }
  // Per-user data in usage metrics for content creators
  {
    name: 'UsageMetricsTrackUserLevelInfo'
    enabled: true
  }
  // Users can connect to data sources by using Apache Arrow database connectivity (ADBC)
  {
    name: 'UseAdbcByDefault'
    enabled: false
    delegateToWorkspace: true
  }
  // Use semantic models across workspaces
  {
    name: 'UseDatasetsAcrossWorkspaces'
    enabled: true
  }
  // Integration with SharePoint and Microsoft Lists
  {
    name: 'VisualizeListInPowerBI'
    enabled: false
  }
  // Web content on dashboard tiles
  {
    name: 'WebContentTilesTenant'
    enabled: false
  }
  // Users can edit semantic models in the Power BI service
  {
    name: 'WebModelingTenantSwitch'
    enabled: true
  }
  // Configure workspace-level inbound network rules
  {
    name: 'WorkspaceBlockInboundAccess'
    enabled: false
  }
  // Configure workspace-level outbound network rules
  {
    name: 'WorkspaceBlockOutboundAccess'
    enabled: false
  }
  // Apply customer-managed keys
  {
    name: 'WorkspaceCmk'
    enabled: false
  }
]

